require:
  - rubocop-rails

AllCops:
 TargetRubyVersion: 3.0
 SuggestExtensions: false
 NewCops: enable
 Exclude:
   - 'vendor/**/*'
   - 'db/**/*'
   - 'bin/**/*'

Style/Documentation:
 Enabled: false

Metrics/BlockLength:
 IgnoredMethods: ['describe', 'context', 'it']
 Exclude:
   - 'config/**/*'

Style/ClassAndModuleChildren:
  EnforcedStyle: 'compact'
  Exclude:
    - 'config/application.rb'
