version: '3'
services:
  web:
    build: .
    command: rails s -b 0.0.0.0
    container_name: rental-cars
    ports:
      - 3000:3000
    volumes:
      - .:/rental-cars
    tty: true
    stdin_open: true
    # env_file:
    #   - .env.docker
    # depends_on:
    #   - db
#   db:
#     image: postgres:14.1
#     env_file:
#       .env.docker
#     volumes:
#       - rental-cars-data:/var/lib/postgresql/data
# volumes:
#   rental-cars-data:
